pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment { 
        prjhome = "/var/jenkins_home/workspace/java-maven-app"
        prjpath = 'simple-java-maven-app'
    }    
    stages {
        stage('Build') {
            steps {
	    	sh "pwd"
    		sh "echo $prjhome"
     		sh "echo $prjpath"
                sh 'cd $prjpath; mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'cd $prjpath; mvn test'
            }
            post {
                always {
                    junit '$prjhome/$prjpath/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh '$prjpath/jenkins/scripts/deliver.sh'
            }
        }
    }
}
